version: 2
jobs:
 
  build-boostedgcc:
    working_directory: ~
    docker:
      - image: micwide/boostedgcc:latest
    steps:
      - checkout
      - run:
          name: Build from source
          command: 'cmake CMakeLists.txt ; make'
      - run:
          name: Install product
          command: 'sudo make install'
      - run:
          name: Test
          command: 'make test'

  build-boostedgcc-update:
    working_directory: ~
    docker:
      - image: micwide/boostedgcc:latest
    steps:
      - checkout
      - run:
          name: Update docker libs
          command: 'apt-get -y update && apt-get -y upgrade'
      - run:
          name: CMake & make
          command: 'cmake CMakeLists.txt ; make'
      - run:
          name: Install product
          command: 'sudo make install'
      - run:
          name: Check if there is any regression
          command: 'make test'

  build-buildpack:
    working_directory: ~
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - run:
          name: Show what I really am
          command: 'uname -a ; cat /proc/version; cat /etc/issue'
      - run:
          name: Install required libs
          command: 'sudo apt-get -y install gcc cmake libboost-all-dev make build-essential'
      - run:
          name: Build from source
          command: 'cmake CMakeLists.txt ; make'
      - run:
          name: Install product 
          command: 'sudo make install'
      - run:
          name: Check if there is any regression
          command: 'make test'

workflows:
  version: 2
  commit:
    jobs:
      - build-buildpack:
          filters:
            branches:
              only: 
                 - master
                 - /issue_.*/
  nightly:
    triggers:
      - schedule:
          # https://crontab.guru/#0_1_*_*_3
          cron: "0 1 * * 3"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-boostedgcc
      - build-boostedgcc-update
      - build-buildpack
